var judges = {
  Arpit:
    "Arpit was the Captain, head choreographer and male lead of the collegiate level Hindi Film Dance Team USC Zeher from 2014-2016. He has been awarded the title of Mr. Bollywood America 2016 & 'Best Male Performer' at the national dance competitions Tufaan 2015 and Jhoomti Shaam 2016. He also led his team to 1st place at Bollywood Berkeley 2016, Nachle Deewane 2016, Iyana 2016, and USC’s Best Dance Crew 2016, and to 2nd place at Jhoomti Shaam 2016. Under his captaincy, the team was titled the Best Female Group in the nation at Bollywood America 2016. He has been pursuing his love for dance for over 13 years now, being informally and self - trained in Bollywood, Bhangra, Raas and Lyrical Hip - Hop. Since his departure from the collegiate circuit, Arpit has had the opportunity to dance with Diljit Dosanjh at the Iifa Awards in 2017. He has been giving back to the collegiate dance community by having judged at competitions such as Jhoomti Shaam, A2 Dhoom, Tamasha SD, UGA India Night, ATL Tamasha & Dance Ke Deewane.",
  Sanjana:
    "Sanjana's journey as a dancer began at a young age with the study of several classical Indian dance forms, including Bharanatyam, Kuchipudi, Mohiniattam, and folk styles. Following over 10 years of training, she completed her arangetram at age 15. She soon immersed herself in the competitive collegiate dance circuit, and is now a veteran of the award- winning all - female fusion team Drexel Jhalak and the all - star exhibition team Aluminati. Inspired early on by the allure of Bollywood cinema, Sanjana has cultivated a deep appreciation for her culture and its emphasis on the arts, and is constantly seeking to expand her repertoire of dance styles. She continues to engage with the Bollywood fusion dance community, having judged more than 20 national competitions to date. Sanjana remains involved as a dancer and judge whilst working in New York City and thanks her family and friends for their continued support of her passion.",
  Sri:
    "Srihari Sritharan is San Diego-based veteran dancer, choreographer, and DJ in the fusion circuit for the past 10 years. Sri danced in undergrad with Brown Badmaash, serving as the most prolific choreographer and internal music chair. He was elected as co-captain his junior and senior year, helping his team place at every competition for 2 straight years, with the central team philosophy of keeping creativity the number one focus over everything else. While in graduate school, Sri took advantage of the tight - knit fusion community in Philly to dance with Penn Dhamaka and Broad Street Baadshahz, as well as a year on First Class Bhangra in Pittsburgh. Since 2015, he has been a dancer and choreographer on Aluminati, continuing to bring his 'old-school' choreo / gimmick heavy mentality to the co - ed alumni exhibition team. Beyond his direct impact on the rosters he danced on, Sri has been instrumental in slowly converting a formerly Bolly / Punjabi dominated scene in the late 2000s to a community that openly loves and enjoys South Indian / Kuthu music and choreography. He had the honor of spreading this love for his culture as an instructor for DDCON alongside Aahlad Vadrevu. Across the years, he has helped over 50 fusion teams with music and creative advising, resulting in several Best Mix Awards and successfully placing teams at the national level. His number one goal as a judge is simple: provide useful feedback to help every team maximize their performance impact, so that they will look back fondly on their videos for years to come.",
  Chintan:
    "Chintan is a Hip Hop and Bhangra dancer and choreographer. He first started dancing when he joined GT Qurbani, a Bollywood Fusion team with which he attended many Fusion competitions. His tenure on Qurbani has given him experience with directing and performing both hip hop, bhangra, and bollywood choreography, and a deep knowledge of what makes a successful performance in the Bollywood Fusion circuit. He now lives in San Francisco, California, and has danced with a few different teams. Academy of Villains is a professional hip hop dance company with branches in both SF and LA. Darzana is an all-male Bollywood Fusion alumni dance team. He has also danced with two bhangra teams - Nachde Shokeen Gabroo, and San Francisco Bhangra Club.",
  Dhruv:
    "Dhruv Naik is a Toronto-based Bollywood fusion dancer and has been dancing for 15 years. He attended Ryerson University, where he was the lead Bollywood choreographer and co-captain of the team for three years. For the past 6 years, Dhruv has been heavily involved with Aluminati (@aluminatidance) and is on the executive board this year, an all-star alumni Bollywood fusion team, and considers them his international dance family. In 2009, Dhruv and his brother co-founded a Bollywood fusion dance company called Jadoo Entertainment (@jadooent), which started out performing at cultural festivals and weddings. As Jadoo grew, it began offering dance classes all across the Greater Toronto Area, and has most recently found success with its critically-acclaimed Bollywood Dance Musical Productions, which were sold out multiple times with Dhruv as one of their principal choreographers and creative directors. Dhruv has also taught at dance conventions such as DDCON multiple times and has throughly enjoyed spreading his love of dance with the world. Dhruv's dance experience centers around Bollywood, hip hop, jazz, and Indian classical, but his aim has always been to expand his skill set to ensure he is able to explore the realm of dance in its entirety. Outside of the studio, you can find Dhruv snacking - he loves food! ",
  Gaurav:
    "Gaurav Gulati found his passion for dance at a very young age through Bollywood Movies and Hip Hop Culture. He began choreographing routines since 8th grade for his High School International Culture Show. After high school, he joined the nationally recognized team, The Wanted Ashiqz, and performed on a variety of platforms such as Bollywood America, World of Dance, and So You Think You Can Dance. Gaurav also danced for the company, Bollywood Performing Arts, where he served as an elite troupe performer and Hip Hop dance instructor. Gaurav stays active in the dance community by creating choreography videos, hosting / attending dance classes, and doing freelance work. In New York, he is also known as part of a performance duo called ‘Fire & Smoke’, where he and his friend fuse styles such as Street Jazz, Bollywood, Hip Hop, and Dancehall. In the past two years, he has danced for Desi artists such as Arjun, PropheC, DixiMusic, SAMAA, Shishi Music, and choreographed a live set for Raja Rose. From 2018 - 2020, Gaurav was a part of the desi circuit's Hip Hop Alumni Team, The Watchlist, where he served as a choreographer and manager. When he is not dancing, Gaurav works full time as a Clinical Laboratory Scientist.",
  Keertana:
    "At a young age, Keertana began professional training in the Indian Classical Dance form, Bharatha Natyam, and completed her Arangetram from the Natya Kala Mandir School of Dance in 2008. Upon entering the University of Maryland, she joined Maryland Dhoom, where she was captain for 2 of her 4 years on the team. Keertana has also been a member of the premier Hip-Hop Dance Team, Major Definition, the all-female, competitive bhangra dance team, DC Bhangra Crew, and Texas A&M's Classical dance team, TAMU Sahithya. Additionally, since 2014, Keertana has been a member of the All-Star Alumni Bollywood fusion dance team, Aluminati, in which she served as the Year 6 Creative Director. Currently Keertana teaches workshops in the DMV area through Desi Moves & Vibes. She is excited to stay involved in the fusion circuit as a judge and cannot wait to see what teams bring to CyberNaach 2020!",
  Keerthana:
    "Keerthana Pakanati grew up juggling her Bharatanatyam bells with her pointe shoes. Her first foray into dance was at the age of 3, when she took her first ballet class. However, it wasn’t until she moved to Texas that her dance journey truly began. At the age of 5, she joined Boni’s Dance and Performing Arts, taking classes in a variety of dance styles, including jazz, tap, hip, hop, and lyrical. Keerthana was a part of The Woodlands Dance Company, Boni’s Ballet Company from 2003 – 2013, dancing as a principal for 2 years where she performed a number of roles in the company’s annual production of The Nutcracker. Simultaneously Keerthana also trained in the Kalakshetra style of Bharatanatyam under the guidance of Guru Padmini Chari of the Nritya School of Dance. She completed her Bharatanatyam Arangetram in 2010. While in college at the University of Texas at San Antonio, Keerthana co-founded UTSA Sapna, an all-female Bollywood - Fusion Dance Team. She served as co - captain from 2013 - 2016, and is incredibly proud to watch the team’s continued growth. In an effort to share her love for Bollywood - fusion dance with the community, Keerthana also co - founded Sitara, San Antonio’s Bollywood - Fusion Dance Competition. She has had the opportunity to judge at numerous comps, including Buckeye Mela, Infusion, Maryland Minza, NDC, Sitara and more! Currently, Keerthana is an Internal Medicine Resident in Austin, Texas and she continues to watch the circuit in awe of the creativity and talent. She is incredibly excited to be a part of the first virtual Bollywood fusion dance comp and can't wait to see what the teams bring! ",
  Nilang:
    "Nilang has been an avid dancer throughout his undergrad, where he began his dancing journey through Ohio State Raas in 2011. Later, he was introduced to the bollywood-fusion dance circuit and joined OSU Genesis. During the three years on this team, he was a dancer, choreographer, and an executive board member. Through Genesis, he developed his expertise in various dance styles such as bhangra, hip-hop, and urban bollywood. His dance experience also extends to lyrical, contemporary, Latin, and ballroom. Following graduation, he joined Aluminati, an all-star alumni bollywood-fusion team, where he also served as a choreographer. After two years on Aluminati, Nilang decided to further his passion for bhangra by joining Dallas-De-Gabroo: Bhangra Express. Currently, Nilang serves as a choreographer and a captain of Lone Star Gabroos, an all-male competitive bhangra team. Under Nilang’s leadership, LSG’s inaugural season in Spring 2018 turned out to be a very successful one through multiple placings. Overall, Nilang has competed at over 20 desi dance competitions across the nation. Additionally, he has four years of judging experience under his belt, having judged at 18 prestigious competitions since 2016. Nilang's active role in these dance teams is matched by his role on Desi Dance Network Inc., as he was one of the first moderators who helped create and foster the network into the non-profit organization that it is today. Outside of dancing, Nilang is a chai coffee fanatic, competitive antakshari player, and puppies are the easiest way to distract him. He is not superstitious, but he is a little stitious.",
  Pranav:
    "Pranav is a professional dancer and choreographer based out of the greater New York City area. His styles include bollywood, bhangra, afro, contemporary, hip hop, and Indian folk. During his tenure both as a dancer and board member of Northwestern Anubhav, the team saw success across the nation, including winning the 2014 Bollywood America National Championship. He has since continued to stay connected to the circuit by being a Director for both SAS and Boston Bhangra Competition from 2016 to 2018 and judging numerous national competitions, including Bollywood America 2019. Professionally, outside of the circuit, he was a founding member and board member for Exodus Artistry with whom he won Season One of Dance USA Dance in 2017. He also toured as a core cast member for Bollywood Boulevard: A Journey Through Hindi Cinema, which began touring in 2017 at the Lincoln Center in NYC. In 2018, Pranav co-founded AfroDesi, a new fusion style merging afro and indo elements. AfroDesi has since had one national and two international tours covering London, Dubai, and Dar Es Salaam. AfroDesi continues to regularly teach in New York, London, and Mumbai.",
  Rohit:
    "Rohit Jethwani is a dancer and choreographer based in Pune, India. His dance journey began about 20 years ago at the age of 4. In his initial training days, he learned from street dancers in Pune. By the age of 9, he enrolled in Shiamak Davar's Institute for Performing Arts. Before he knew it, he was selected in Shiamak's “Showkids” and got the opportunity to perform with the troupe at 30+ shows across India. He trained at the academy for 6 years where he learned various styles such as Bollywood, Bollyhop, Contemporary, Afro Jazz, and Indo Jazz. Unfortunately, he had to discontinue his training there because he wanted to pursue higher education at the University of Southern California (USC) and moved to Los Angeles. While at USC, he joined its national award-winning competitive Bollywood Dance team: USC Zeher. He was on the team for 3 years and was elected as captain and male lead dancer in his last year. During his tenure as captain and lead dancer, he led his team to win several competitions and broke the record for receiving four“Best Male Lead” awards in one season. Through his experience in the DDN circuit he was amazed to see how well Bollywood was fused with different styles like Hip Hop and Jazz popularly termed as Bollywood Fusion. Though he found it unique, he felt it took away from the original Bollywood style. Upon graduation, he co-founded Garv with a mission to spread authentic Bollywood dance style across the United States and the entire world. At Garv, he taught several sold out international workshops in USA and India and produced viral dance content grossing over 11 million views on Youtube. After leading Garv for 1.5 years he realized his co-founder and him had different individual goals so they decided to disband Garv and continued to pursue dance as individual artists. Now, he has moved back to India to pursue his dream of performing on the big screen as an actor or a Bollywood movie choreographer. At present, as a freelance choreographer, he teaches workshops and is popularly known as “juniorjethu” on Instagram. He has collaborated with some of the top content creators in the dance industry like TeamNaach and has produced 20+ videos grossing millions of views on Instagram and Youtube.",
  Vikram:
    "Vikram Eagam is currently a consultant in Chicago, IL and has over 10 years of dance and competition experience. Vikram has danced on and captained fusion, garba-raas, and bhangra teams over the years and has judged competitions since 2013, including Bollywood America and South Asian Showdown. He was the founder of Boston University Khatarnak, and has also danced with a myriad of bhangra teams, including MOB Chicago, Dub City Bhangra, and MIT Bhangra. Additionally, he has judged at Bollywood America, South Asian Showdown, Derby City Dhoom, as well as many other local competitions in Florida! He also has experience judging bhangra competitions, including Derby City Dhoom and Vice City Bhangra. As someone who found much joy and solace in dancing and competing, Vikram is excited to judge CyberNaach during these unprecedented times.",
  Anu:
    "Anu Mysore is a New Jersey based dancer, choreographer, and dance instructor. Anu has worked as a choreographer for 13 years between 2 leading NJ dance companies and has taught several students - many of whom have gone on to become a part of the DDN circuit. She has learned several styles and continues to train by attending workshops, masterclasses, and conventions including DDCON. In addition to being a dancer, Anu is a singer and actress as well. She was recently seen in 'Bollywood Boulevard' and is currently working on a musical theater project with La Jolla Playhouse. Anu's favorite dance memory is learning from the legendary Saroj Khan and receiving personal recognition when she praised Anu's grace and facial expression.",
  Shatakshi:
    "Shatakshi has been classically trained in Bharatnatyam for 12 years and has been doing Bollywood for 17 years. She also has experience in contemporary, hip hop and  bhangra. During her time in the circuit, Shatakshi was Captain of UNC Chalkaa for 2 years and Director of AKD 2017. She was also a part of Khiladis for a year.  After graduation, Shatakshi has been engaged with the circuit by being a judge at various competitions. She is currently affiliated with Ayana Arts based in NYC.",
  Shriya:
    "Shriya Kannan is a dancer and choreographer from Boston, MA. She has over 25 years of experience in Bharatanatyam, having trained and performed professionally in India under Kalaimamani Guru Rhadha. Since her arangetram in 2009 she has performed at various prestigious venues around the world including: Sri Brahmostsava Festival in Bangalore, Krishna Gana Sabha in Chennai, and the Cleveland Thyagaraja Aradhana.Shriya co-founded Case Kismat Fusion Dance Team and, during her 3 years as captain, choreographed several award winning Bollywood - fusion routines. While in college Shriya was also member of hip - hop / jazz group, Spartan Dance Team, and raas team, Case Raas Goondas. After graduating, Shriya has continued to pursue her passion as a dancer. Since 2015 she has been a dancer and choreographer of the All-Star Alumni Bollywood-fusion dance team, Aluminati and performed with them at Bollywood America, Legends Bollywood Fusion Dance Championship, and World of Dance. For the past year she has also been a choreographer for KuthuHop, a fusion group that combines kuthu and hip - hop techniques. With KuthuHop, Shriya teaches workshops in the greater Boston area and has collaborated with desi - fusion dancers from across the country to create several videography projects.",
};

function replaceText(name) {
  document.getElementById("bio").innerHTML = judges[name];
  document.getElementById("bioheader").innerHTML = "About " + name;
}
